### ISSUE TITLE
BadRequest when using Set-AzureRmIotHub to change the SKU of IOT hub

### ISSUE THREAD

**Issue by HsiaoH** [Azure/azure-docs-powershell#772]
I am getting a BadRequest when using the following command:

    Set-AzureRmIotHub -ResourceGroupName "myresourcegroupname" -Name "iothubname" -SkuName S2 

Running  Resolve-AzureRmError -Last:

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.IotHub.IotHubResourceOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.IotHub.IotHubResourceOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.CreateOrUpdate(IIotHubResourceOperations operations, String resourceGroupName, String resourceName, IotHubDescription iotHubDescription, String
                 ifMatch)
                    at Microsoft.Azure.Commands.Management.IotHub.SetAzureRmIotHub.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.IotHub.Models.ErrorDetailsException
InvocationInfo : {Set-AzureRmIotHub}
Line           : Set-AzureRmIotHub -ResourceGroupName "myresourcegroupname" -Name "iothubname"
Position       : At line:1 char:1
                 + Set-AzureRmIotHub -ResourceGroupName "myresourcegroupname" -Name "io ...
                 +

**Comment by sptramer** [comment]
@HsiaoH - This is an engineering issue. Please file a product bug: https://github.com/azure/azure-powershell/issues
