### ISSUE TITLE
Not compatible with Azure CLI (MSI)

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-docs-powershell#827]
It looks as though one cannot have AZ PowerShell and AZ CLI (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest) coexisting on the same PC.

I had AZ CLI installed and working. I installed AZ PowerShell and now, when I run `az`, I get a load of jibberish. It doesn't matter if I run it in DOS or PowerShell or what command I run. `az` on its own is enough to produce this.

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli\azure\cli\__main__.py", line 32, in <module>
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\__init__.py", line 515, in get_default_cli
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\__init__.py", line 55, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\cloud.py", line 305, in get_active_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\cloud.py", line 294, in get_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\cloud.py", line 247, in _get_cloud
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-homc4z86\azure-cli-core\azure\cli\core\cloud.py", line 265, in get_clouds
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\john\\.azure\\clouds.config', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

```

What is really frustrating is that I can't get AZ CLI to work, even after removing AZ PowerShell, rebooting, reinstall AZ CLI etc. 

In theory, one would hope that I could live with just one of them, but I need PowerShell for a plethora of existing code and it seems that Terraform doesn't understand the token created by AZ PowerShell, but is happy with AZ CLI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65abff75-73f1-3033-d816-e03e0d7fe4ff
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/new-azureps-module-az.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/new-azureps-module-az.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@arcotek-ltd - This sounds like a product issue. Please file a bug report with both the CLI engineering team and Azure PowerShell:

* [Azure CLI issues](https://github.com/Azure/azure-clil/issues)
* [Azure PowerShell issues](https://github.com/Azure/azure-powershell/issues)
